// packages/react/src/hooks.ts
import { useCallback, useEffect, useReducer, useMemo } from "react";
import type { Locale, MessageKey, TranslateContext, TranslateFunction } from "@fanee/core";
import { useRuntime } from "./provider";

function useRuntimeVersion(): number {
	const runtime = useRuntime();
	const [version, bump] = useReducer((v: number) => v + 1, 0);

	useEffect(() => {
		return runtime.subscribe(() => {
			bump();
		});
	}, [runtime]);

	return version;
}

/**
 * Subscribe to the Fanee runtime and access it alongside the current locale.
 *
 * @returns An object with the runtime and the active locale.
 *
 * @example
 * ```tsx
 * const { runtime, locale } = useFanee();
 * ```
 */
export function useFanee(): { runtime: ReturnType<typeof useRuntime>; locale: Locale } {
	const runtime = useRuntime();
	const locale = useLocale();
	return useMemo(() => ({ runtime, locale }), [runtime, locale]);
}

/**
 * Return a translation function bound to the current runtime state and
 * an optional namespace/locale context.
 *
 * The returned function is recreated whenever the active locale, namespace,
 * or underlying resources change, so it remains reactive to runtime updates.
 *
 * @param context - Optional locale/namespace overrides.
 * @returns A `(key, vars?) => string` translate function.
 *
 * @example
 * ```tsx
 * const t = useT({ namespace: "errors" });
 * return <p>{t("not_found")}</p>;
 * ```
 */
export function useT(context?: Partial<TranslateContext>): TranslateFunction {
	const runtime = useRuntime();
	const version = useRuntimeVersion();
	const locale = context?.locale;
	const namespace = context?.namespace;

	// biome-ignore lint/correctness/useExhaustiveDependencies: version forces update on resource changes
	return useCallback(
		(key: MessageKey, vars?: Record<string, unknown>) => {
			const result = runtime.getT({ locale, namespace })(key, vars);
			return result;
		},
		[runtime, locale, namespace, version]
	);
}

/**
 * Read the currently active locale from the runtime.
 *
 * @returns The BCP-47 locale tag.
 */
export function useLocale(): Locale {
	const runtime = useRuntime();
	useRuntimeVersion();
	return runtime.getLocale();
}

/**
 * Return a setter for the runtime locale.
 *
 * @returns A function that updates the active locale.
 */
export function useSetLocale(): (locale: Locale) => void {
	const runtime = useRuntime();
	return useCallback((locale: Locale) => runtime.setLocale(locale), [runtime]);
}

// packages/solid/src/hooks.ts
import { createMemo, type Accessor } from "solid-js";
import type { Locale, MessageKey, TranslateContext, TranslateFunction } from "@fanee/core";
import { useFaneeContext } from "./provider";

/**
 * Subscribe to the Fanee runtime and access it alongside the current locale.
 *
 * @returns An object with the runtime and a reactive locale accessor.
 *
 * @example
 * ```tsx
 * const { runtime, locale } = useFanee();
 * <p>Current locale: {locale()}</p>
 * ```
 */
export function useFanee(): { runtime: ReturnType<typeof useFaneeContext>["runtime"]; locale: Accessor<Locale> } {
	const { runtime, locale } = useFaneeContext();
	return { runtime, locale };
}

/**
 * Return a reactive translation function bound to the current runtime state and
 * an optional namespace/locale context.
 *
 * The returned function automatically re-evaluates when the active locale,
 * namespace, or underlying resources change.
 *
 * @param context - Optional locale/namespace overrides, or a functional getter to track dynamic property changes.
 * @returns A `(key, vars?) => string` translate function.
 *
 * @example
 * ```tsx
 * const t = useT({ namespace: "errors" });
 * return <p>{t("not_found")}</p>;
 * ```
 */
export function useT(context?: Partial<TranslateContext> | (() => Partial<TranslateContext>)): TranslateFunction {
	const { runtime, version } = useFaneeContext();
	const normalizeContext = typeof context === "function" ? context : () => context ?? {};

	const tFn = createMemo(() => {
		version();
		const ctx = normalizeContext();
		return runtime.getT({ locale: ctx.locale, namespace: ctx.namespace });
	});

	return (key: MessageKey, vars?: Record<string, unknown>) => tFn()(key, vars);
}

/**
 * Read the currently active locale from the runtime as a reactive accessor.
 *
 * @returns A reactive accessor for the BCP-47 locale tag.
 */
export function useLocale(): Accessor<Locale> {
	const { locale } = useFaneeContext();
	return locale;
}

/**
 * Return a setter for the runtime locale.
 *
 * @returns A function that updates the active locale.
 */
export function useSetLocale(): (locale: Locale) => void {
	const { runtime } = useFaneeContext();
	return (locale: Locale) => runtime.setLocale(locale);
}
